title: Ram Raghu Sankar
logo: /assets/img/Headshot.jpg
#description: text below image
social-network-links:
  github: https://github.com/rrsankar
  twitter: https://x.com/ramrsankar
  linkedin: https://www.linkedin.com/in/ramrsankar/
show_downloads: true
theme: jekyll-theme-minimal   # https://pages.github.com/themes/
